name: Test Project

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        container: node:18
        steps:
            - name: Say Hello
              run: echo Ready to test your code

            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Cache dependencies
              uses: actions/cache@v3
              id: cache
              with:
                path: node_modules
                key: deps-node-modules-${{ hashFiles('**/package.json') }}
            
            - name: Install Docker CLI
              run: |
                apt-get update
                apt-get install -y docker.io

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2
              with:
                install: true

            - name: Install dependencies
              run: npm install
            
            - name: Run test
              run: npm test

            - name: Build Docker image
              run: docker build .
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Say Hello
              run: echo Ready to test your code

            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Load & cache dependencies
              uses: ./.github/actions/cache-deps
              id: cache
            
            - name: Build
              run: npm run build

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                    name: dist-files
                    path: |
                        dist
                        package.json

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v3
              with:
                name: dist-files
            
            - name: Deploy
              run: ls



    lint:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Say Hello
              run: echo Ready to test your code

            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Cache dependencies
              uses: actions/cache@v3
              id: cache
              with:
                path: node_modules
                key: deps-node-modules-${{ hashFiles('**/package.json') }}

            - name: install dependencies
              run: npm install
            
            - name: Lint
              run: npm run lint