name: Test Project

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo Ready to test your code

            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package.json') }}

            - name: install dependencies
              run: npm install
            
            - name: Run test
              run: npm test
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Say Hello
              run: echo Ready to test your code

            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package.json') }}

            - name: install dependencies
              run: npm install
            
            - name: Build
              run: npm run build

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                    name: dist-files
                    path: |
                        dist
                        package.json

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v3
              with:
                name: dist-files
            
            - name: Deploy
              run: ls



    lint:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Say Hello
              run: echo Ready to test your code

            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package.json') }}

            - name: install dependencies
              run: npm install
            
            - name: Lint
              run: npm run lint