name: Test Project

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo Ready to test your code

            - name: Checkout code
              uses: actions/checkout@v3

            - name: install dependencies
              run: npm install
            
            - name: Run test
              run: npm test